import { HSKLevel, LessonType, Module } from '../../types';

export const HSK2_LESSON_3: Module = {
  "id": "hsk2-m3",
  "level": HSKLevel.HSK2,
  "title": "Colors & Possessions (Lesson 3)",
  "description": "Describing objects by color and position. Using \"de\" for possession.",
  "lessons": [
    {
      "id": "hsk2-l3-texts",
      "title": "Texts & Grammar",
      "type": LessonType.GRAMMAR,
      "content": "\n# Text 1: 在房间 (In the room)\n\n<strong>A: 这块手表是你的吗？</strong>\n<em>Zhè kuài shǒubiǎo shì nǐ de ma?</em>\n(Is this watch yours?)\n\n<strong>B: 不是我的。是我爸爸的。</strong>\n<em>Bú shì wǒ de. Shì wǒ bàba de.</em>\n(No, it's not mine. It's my dad's.)\n\n<strong>A: 多少钱买的？</strong>\n<em>Duōshao qián mǎi de?</em>\n(How much was it?)\n\n<strong>B: 三千多块。</strong>\n<em>Sānqiān duō kuài.</em>\n(More than 3000 yuan.)\n\n---\n\n# Text 2: 在家里 (At home)\n\n<strong>A: 这是今天早上的报纸吗？</strong>\n<em>Zhè shì jīntiān zǎoshang de bàozhǐ ma?</em>\n(Is this this morning's newspaper?)\n\n<strong>B: 不是，是昨天的。</strong>\n<em>Bú shì, shì zuótiān de.</em>\n(No, it's yesterday's.)\n\n<strong>A: 你听，是不是送报纸的来了？</strong>\n<em>Nǐ tīng, shì bu shì sòng bàozhǐ de lái le?</em>\n(Listen, is that the newspaper delivery person?)\n\n<strong>B: 我看一下。不是，是送牛奶的。</strong>\n<em>Wǒ kàn yíxià. Bú shì, shì sòng niúnǎi de.</em>\n(Let me check. No, it's the milk delivery person.)\n\n---\n\n# Text 3: 在家里 (At home)\n\n<strong>A: 这是谁的房间？</strong>\n<em>Zhè shì shéi de fángjiān?</em>\n(Whose room is this?)\n\n<strong>B: 这是我和我丈夫的，旁边那个小的房间是我女儿的。</strong>\n<em>Zhè shì wǒ hé wǒ zhàngfu de, pángbiān nàge xiǎo de fángjiān shì wǒ nǚ'ér de.</em>\n(This is mine and my husband's. The small room next to it is my daughter's.)\n\n<strong>A: 你女儿的房间真漂亮！都是粉色的。</strong>\n<em>Nǐ nǚ'ér de fángjiān zhēn piàoliang! Dōu shì fěnsè de.</em>\n(Your daughter's room is so pretty! It's all pink.)\n\n<strong>B: 是啊，粉色是我女儿最喜欢的颜色。</strong>\n<em>Shì a, fěnsè shì wǒ nǚ'ér zuì xǐhuan de yánsè.</em>\n(Yes, pink is my daughter's favorite color.)\n\n---\n\n# Text 4: 在办公室 (In the office)\n\n<strong>A: 你看见我的杯子了吗？</strong>\n<em>Nǐ kànjiàn wǒ de bēizi le ma?</em>\n(Have you seen my cup?)\n\n<strong>B: 这里有几个杯子，哪个是你的？</strong>\n<em>Zhèlǐ yǒu jǐ ge bēizi, nǎge shì nǐ de?</em>\n(There are a few cups here, which one is yours?)\n\n<strong>A: 左边那个红色的是我的。</strong>\n<em>Zuǒbian nàge hóngsè de shì wǒ de.</em>\n(The red one on the left is mine.)\n\n<strong>B: 给你。</strong>\n<em>Gěi nǐ.</em>\n(Here you go.)\n\n---\n\n# Grammar Notes\n\n## 1. The \"的\" Phrase\nWhen pronouns, adjectives, or verbs are followed by \"的\", they form a phrase equivalent to a noun phrase with the head noun omitted.\n\n1.  这本书不是我的。 (This book is not **mine**.) *[=我的书]*\n2.  这个杯子是昨天买的。 (This cup is **the one bought yesterday**.) *[=昨天买的杯子]*\n3.  这块手表是你的吗？ (Is this watch **yours**?) *[=你的手表]*\n\n## 2. Usage of \"一下\" (yíxià)\nUsed after a verb to indicate a short action, similar to reduplicating the verb.\n\n*   我<strong>看一下</strong>。 (Let me have a look.)\n*   你<strong>休息一下</strong>吧。 (You should rest a bit.)\n*   我<strong>问一下</strong>老师。 (Let me ask the teacher.)\n\n## 3. Modal Adverb \"真\" (zhēn)\nUsed before adjectives to express an exclamation, meaning \"really\" or \"indeed\".\n\n*   你<strong>真</strong>好！ (You are really good!)\n*   今天天气<strong>真</strong>好！ (The weather is really good today!)\n*   你女儿的房间<strong>真</strong>漂亮！ (Your daughter's room is really pretty!)\n"
    },
    {
      "id": "hsk2-l3-vocab",
      "title": "New Words",
      "type": LessonType.VOCABULARY,
      "content": "\n# New Words\n\n| Hanzi | Pinyin | Part of Speech | Meaning |\n| :--- | :--- | :--- | :--- |\n| <strong>手表</strong> | shǒubiǎo | n. | watch |\n| <strong>千</strong> | qiān | num. | thousand |\n| <strong>报纸</strong> | bàozhǐ | n. | newspaper |\n| <strong>送</strong> | sòng | v. | to send, to deliver |\n| <strong>一下</strong> | yíxià | m. | once, a bit |\n| <strong>牛奶</strong> | niúnǎi | n. | milk |\n| <strong>房间</strong> | fángjiān | n. | room |\n| <strong>丈夫</strong> | zhàngfu | n. | husband |\n| <strong>旁边</strong> | pángbiān | n. | beside, side |\n| <strong>真</strong> | zhēn | adv. | really, indeed |\n| <strong>粉色</strong> | fěnsè | n. | pink color |\n| <strong>粉</strong> | fěn | adj. | pink |\n| <strong>颜色</strong> | yánsè | n. | color |\n| <strong>左边</strong> | zuǒbian | n. | left side |\n| <strong>红色</strong> | hóngsè | n. | red color |\n| <strong>红</strong> | hóng | adj. | red |\n"
    },
    {
      "id": "hsk2-l3-exercise",
      "title": "Exercises & Culture",
      "type": LessonType.EXERCISE,
      "content": "\n# Warm-up\n\n<strong>Match the words with the corresponding images (Mental Exercise)</strong>\n\n1.  <strong>手表</strong> (shǒubiǎo) - <em>Match with Image B (Watch)</em>\n2.  <strong>报纸</strong> (bàozhǐ) - <em>Match with Image A (Newspaper rack)</em>\n3.  <strong>牛奶</strong> (niúnǎi) - <em>Match with Image C (Milk)</em>\n4.  <strong>房间</strong> (fángjiān) - <em>Match with Image E (Bedroom)</em>\n5.  <strong>丈夫</strong> (zhàngfu) - <em>Match with Image F (Husband/Wife)</em>\n6.  <strong>红色</strong> (hóngsè) - <em>Match with Image D (Red color)</em>\n\n---\n\n# Comprehension Questions\n\n1.  <strong>爸爸的手表多少钱？</strong>\n    <em>Bàba de shǒubiǎo duōshao qián?</em>\n    (How much is Dad's watch?)\n2.  <strong>送报纸的来了吗？</strong>\n    <em>Sòng bàozhǐ de lái le ma?</em>\n    (Did the newspaper delivery person come?)\n3.  <strong>旁边那个小的房间是谁的？</strong>\n    <em>Pángbiān nàge xiǎo de fángjiān shì shéi de?</em>\n    (Whose is the small room on the side?)\n4.  <strong>她女儿的房间怎么样？</strong>\n    <em>Tā nǚ'ér de fángjiān zěnmeyàng?</em>\n    (How is her daughter's room?)\n5.  <strong>哪个杯子是她的？</strong>\n    <em>Nǎge bēizi shì tā de?</em>\n    (Which cup is hers?)\n\n---\n\n# Phonetics: Stress in Four-Syllable Words\n\n<strong>(1) Without Neutral Tone</strong>\nStress is usually on the 4th syllable.\n*   <strong>公共汽车</strong> (gōnggòng qìchē) - Bus\n*   <strong>名胜古迹</strong> (míngshèng gǔjì) - Historical sites\n\n<strong>(2) With Neutral Tone</strong>\nUsually adjectives. Stress on the 4th syllable, 2nd is neutral.\n*   <strong>哆哆嗦嗦</strong> (duōduosuōsuō) - Trembling\n*   <strong>噼里啪啦</strong> (pīlipālā) - Crackling sound\n\n---\n\n# Characters\n\n<strong>1. Strokes</strong>\n*   <strong>横折斜钩 (héngzhéxiégōu):</strong> e.g., <strong>飞</strong> (fēi), <strong>风</strong> (fēng)\n*   <strong>弯钩 (wāngōu):</strong> e.g., <strong>狗</strong> (gǒu), <strong>猫</strong> (māo)\n\n<strong>2. Single Component Characters</strong>\n*   <strong>手 (shǒu):</strong> Hand.\n*   <strong>丈 (zhàng):</strong> Unit of length (originally an elder with a cane).\n*   <strong>夫 (fū):</strong> Husband/Man.\n\n<strong>3. Radicals</strong>\n*   <strong>木</strong> (Wood): <strong>杯</strong> (bēi - cup), <strong>椅</strong> (yǐ - chair).\n*   <strong>刂</strong> (Knife): <strong>别</strong> (bié - separate), <strong>到</strong> (dào - arrive).\n\n---\n\n# Activity: Describing Items\n\nIn pairs, put some items together (pens, books, cups) and ask each other to identify whose is whose based on color and position.\n\n*   A: <strong>这个红色的杯子是你的吗？</strong> (Is this red cup yours?)\n*   B: <strong>不是我的。</strong> (No, it's not mine.)\n*   A: <strong>旁边粉色的杯子是你的吗？</strong> (Is the pink cup next to it yours?)\n*   B: <strong>是我的。</strong> (Yes, it's mine.)\n"
    }
  ]
};
